#!/usr/bin/awk -f

BEGIN {
	FS="	"
	OFS=","
	print "INSERT into bano (lon, lat, elv, lid, bldg)"
	print "VALUES "
	}
	
{
#	print "("$1" , "$2", "$3", '"$4"', '"$5"' ),"
	printf "\(%4.13F, %4.13F, %4.13F, '%s', '%s'\),\n", $1, $2, $3, $4, $5
}

END {
	;
}
