#!/usr/bin/awk -f

BEGIN {
	FS=","
	print "INSERT into Bldg (Bldg_id, Lat, Lng, Ele, r_num, l_id)"
	print "VALUES "
	}
	
{
	print "("$1" , "$2", "$2", "$4", '"$5"', '"$6"' ),"
}

END {
	;
}
